version: 0.2

phases:
  install:
    commands:
      - echo git:"$CODEBUILD_SOURCE_REPO_URL" and branch:"$CODEBUILD_SOURCE_VERSION"
      - apt-get install zip
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - cd src
      - dotnet restore
      - dotnet build -c Release
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
      - cd $CODEBUILD_SRC_DIR/src/WebApp/bin/Release/netcoreapp1.1 && zip -r WebApp.zip .
      - cd $CODEBUILD_SRC_DIR
artifacts:
  discard-paths: no
  files:
    - '**/*'
