version: 0.2

phases:
  install:
    commands:
      - printenv
      - apt-get install mono-runtime mono-complete libmono-system-core4.0-cil
      - curl -Lsfo cake.sh http://cakebuild.net/download/bootstrapper/linux
      - chmod +x cake.sh
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - ./cake.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  discard-paths: no
  base-directory: artifacts
  files:
    - '**/*'
