version: 0.2
 
phases:
  install:
    commands:
      - echo CODEBUILD_SRC_DIR $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_SOURCE_REPO_URL $CODEBUILD_SOURCE_VERSION
      - echo CODEBUILD_RESOLVED_SOURCE_VERSION $CODEBUILD_RESOLVED_SOURCE_VERSION
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - cd src
      - dotnet restore
      - dotnet build -c Release
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  discard-paths: no
  files:
    - '**/*'
