version: 0.2
 
phases:
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - cd src
      - dotnet restore
      - dotnet build -c Release
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $CODEBUILD_SRC_DIR
artifacts:
  discard-paths: no
  files:
    - '**/*'
