version: 0.2

phases:
  install:
    commands:
      - printenv
      - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      - echo "deb http://download.mono-project.com/repo/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/mono-official.list
      - sudo apt-get update
      - sudo apt-get --yes --force-yes install mono-runtime mono-complete libmono-system-core4.0-cil
  pre_build:
    commands:
      - curl -Lsfo cake.sh http://cakebuild.net/download/bootstrapper/linux
      - chmod +x cake.sh
      - echo Build started on `date`
  build:
    commands:
      - ./cake.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: artifacts
  discard-paths: no
  files:
    - '**/*'
